version: '2'
services:
  web:
    build: .
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "80:80"
      - "443:443"
    environment:
      PORT: 443
      HOST: 0.0.0.0